#pragma once

#include "resource.h"
#include "Debug.h"
#include "BMP.h"
#include "graphic.h"
#include "GameObject.h"
#include "graphic.h"
#include "ObjectManager.h"
#include "Sprite.h"
#include "Time.h"
#include "GameBG.h"
#include "Player.h"
#include "Input.h"
#include "Laser.h"
#include "Animation.h"
#include "Enemy.h"
#include "BoxCollider2D.h"
#include "LaserExp.h"
#include "EnemyExp.h"
#include "EnemyBullet.h"
#include "BulletExp.h"
#include "PlayerExp.h"
#include "EnemySpawner.h"
#include "GameManager.h"
#include "Random.h"
#include "GameOver.h"
#include "Bomb.h"
#include "BombExp.h"
#include "Shield.h"
#include "BulletItem.h"
#include "BombItem.h"
#include "Boss.h"
#include "Propeller.h"
#include "Wing.h"
#include "Gun.h"
#include "Cannon.h"
#include "Radar.h"
#include "BossSpriteChild.h"
#include "DeadBoss.h"
#include "CannonBall.h"
#include "Button.h"
#include "BTNExit.h"
#include "BTNPause.h"
#include "Application.h"

#define WIDTH  480  //게임장면..가로크기
#define HEIGHT 800  //게임장면..세로크기